# Renan user

apiVersion: configuration.konghq.com/v1
kind: KongConsumer
metadata:
  name: consumer-renan-customer-acceptance
  namespace: hello-world
  annotations:
    kubernetes.io/ingress.class: "kong"
  labels:
    app.kubernetes.io/name: api-kongconsumer
    app.kubernetes.io/instance: api-customer-acceptance
    app.kubernetes.io/managed-by: kong-acceptance
    environment: acceptance
    app.kubernetes.io/component: kongconsumer
    app.kubernetes.io/part-of: api
username: renan
custom_id: renan

---

apiVersion: configuration.konghq.com/v1
kind: KongCredential
metadata:
  name: credential-renan-customer-acceptance
  namespace: hello-world
  annotations:
    kubernetes.io/ingress.class: "kong"
  labels:
    app.kubernetes.io/name: api-kongcredential
    app.kubernetes.io/instance: api-customer-acceptance
    app.kubernetes.io/managed-by: kong-acceptance
    environment: acceptance
    type: acl
    app.kubernetes.io/component: kongcredential
    app.kubernetes.io/part-of: api
consumerRef: consumer-renan-customer-acceptance
type: basic-auth
config:
  username: renan
  password: RENAN_PASSWORD

---

apiVersion: configuration.konghq.com/v1
kind: KongCredential
group: contributors
metadata:
  name: credentials-renan-customer-acceptance-acl
  namespace: hello-world
  annotations:
    kubernetes.io/ingress.class: "kong"
  labels:
    app.kubernetes.io/name: api-kongcredential
    app.kubernetes.io/instance: api-customer-acceptance
    app.kubernetes.io/managed-by: kong-acceptance
    environment: acceptance
    type: acl
    app.kubernetes.io/component: kongcredential
    app.kubernetes.io/part-of: api
consumerRef: consumer-renan-customer-acceptance
type: acl
config:
  group: "contributors"

---

# Aya's user

apiVersion: configuration.konghq.com/v1
kind: KongConsumer
metadata:
  name: consumer-aya-customer-acceptance
  namespace: hello-world
  annotations:
    kubernetes.io/ingress.class: "kong"
  labels:
    app.kubernetes.io/name: api-kongconsumer
    app.kubernetes.io/instance: api-customer-acceptance
    app.kubernetes.io/managed-by: kong-acceptance
    environment: acceptance
    app.kubernetes.io/component: kongconsumer
    app.kubernetes.io/part-of: api
username: aya
custom_id: aya

---

apiVersion: configuration.konghq.com/v1
kind: KongCredential
metadata:
  name: credential-aya-customer-acceptance
  namespace: hello-world
  labels:
    app.kubernetes.io/name: api-kongcredential
    app.kubernetes.io/instance: api-customer-acceptance
    app.kubernetes.io/managed-by: kong-acceptance
    environment: acceptance
    type: acl
    app.kubernetes.io/component: kongcredential
    app.kubernetes.io/part-of: api
consumerRef: consumer-aya-customer-acceptance
type: basic-auth
config:
  username: aya
  password: AYA_PASSWORD

---

apiVersion: configuration.konghq.com/v1
kind: KongCredential
group: owners
metadata:
  name: credentials-aya-customer-acceptance-acl
  namespace: hello-world
  annotations:
    kubernetes.io/ingress.class: "kong"
  labels:
    app.kubernetes.io/name: api-kongcredential
    app.kubernetes.io/instance: api-customer-credentials
    app.kubernetes.io/managed-by: kong-acceptance
    environment: acceptance
    type: acl
    app.kubernetes.io/component: kongcredential
    app.kubernetes.io/part-of: api
consumerRef: consumer-aya-customer-acceptance
type: acl
config:
  group: "owners"
