apiVersion: v1
kind: Secret
metadata:
  name: kong-pg-secrets
  namespace: kong
type: Opaque
data:
  username: ZmFrZS12YWx1ZQ==
  password: ZmFrZS12YWx1ZQ==
  host: ZmFrZS12YWx1ZQ==
  database: ZmFrZS12YWx1ZQ==
